//these are rooms, they could be like conversations
//its and 8x8 grid starting at 06, turns left at 0, 
//extends hall to 8, 16, 24, 32, 40, 48. 52
//next hall is 52 to 63 
var rooms = {
    room: [
        { name: "corner", "description": ["you can turn left here if you want"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: null, "description": ["you can't do that"] },
        { name: "corner", "description": ["you can turn left here if you want"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: "hall", "description": ["it's a hall of art, look aroud"] },
        { name: "hall", "description": ["dead end"] },
    ]
}
